#### Getting help with builtin documentation
Most jupyter notebook enviroments will provide short documentation when either
1. Placing the cursor in between empty parantheses (e.g. Google collab)

In [1]:
from qc_education_package import Simulator
sim = Simulator(1)

sim.had()  # place cursor in between parantheses to show documentation

array([[ 0.70710678,  0.70710678],
       [ 0.70710678, -0.70710678]])

2. Execute ```help(...)```

In [2]:
help(sim.had)

Help on method had in module qc_education_package.simulator:

had(qubit=None) -> <built-in function array> method of qc_education_package.simulator.Simulator instance
    Applies the hadamard gate to given qubit(s).
    If no qubit is given (qubit=None) hadamard gate will be applied to all qubits.
    
    Args:
        qubit (int or list(int), optional): qubit(s) to apply HAD to. Defaults to None.
    
    Returns:
        np.array: Matrix for hadamard gate on given qubit in comp. basis.



3 Execute with tailing ```?``` in cell

In [8]:
sim.had?

Signature: sim.had(qubit=None) -> <built-in function array>
Docstring:
Applies the hadamard gate to given qubit(s).
If no qubit is given (qubit=None) hadamard gate will be applied to all qubits.

Args:
    qubit (int or list(int), optional): qubit(s) to apply HAD to. Defaults to None.

Returns:
    np.array: Matrix for hadamard gate on given qubit in comp. basis.
File:      ~/Seafile/Uni/Austausch Max Niki/dcn_examples/.venv/lib/python3.10/site-packages/qc_education_package/simulator.py
Type:      method

## Single qubit gates

In [7]:
from qc_education_package import Simulator, CircleNotation, DimensionalCircleNotation
sim = Simulator(3)

In [8]:
sim.had(1)
sim.qnot(1)

array([[0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j]])

Pauli-Gates

In [ ]:
sim.x(1)  # equals qnot(1)
sim.y(1)
sim.z(1)  # equals phase(1, 180)
sim.flip(1)  # alias for z(1)

Root Gates

In [ ]:
sim.rootX(1)
sim.rootNot(1)  # alias for rootX
sim.rootZ(1)

## Phase Gates

### fixed-angle

In [ ]:
sim.s(1)  # equals phase(1, 90) -> 90 deg Phase gate
sim.t(1)  # equals phase(1, 45) -> 45 deg Phase gate

Variable angle (in deg)

In [ ]:
angle = 90  # deg
sim.phase(1, angle)

## Bloch sphere rotations

In [4]:
sim.rx(90, 1)  # Rx gate
sim.ry(90, 1)  # Ry gate
sim.rz(90, 1)  # Rz gate


array([[0.70710678-0.70710678j, 0.        +0.j        ],
       [0.        +0.j        , 0.70710678+0.70710678j]])

Multi Qubit gates

In [9]:
sim.had(1)  # apply to single qubit
sim.had([1,2])  # apply to multiple qubits
sim.had()  # apply to all qubits

array([[ 0.35355339,  0.35355339,  0.35355339,  0.35355339,  0.35355339,
         0.35355339,  0.35355339,  0.35355339],
       [ 0.35355339, -0.35355339,  0.35355339, -0.35355339,  0.35355339,
        -0.35355339,  0.35355339, -0.35355339],
       [ 0.35355339,  0.35355339, -0.35355339, -0.35355339,  0.35355339,
         0.35355339, -0.35355339, -0.35355339],
       [ 0.35355339, -0.35355339, -0.35355339,  0.35355339,  0.35355339,
        -0.35355339, -0.35355339,  0.35355339],
       [ 0.35355339,  0.35355339,  0.35355339,  0.35355339, -0.35355339,
        -0.35355339, -0.35355339, -0.35355339],
       [ 0.35355339, -0.35355339,  0.35355339, -0.35355339, -0.35355339,
         0.35355339, -0.35355339,  0.35355339],
       [ 0.35355339,  0.35355339, -0.35355339, -0.35355339, -0.35355339,
        -0.35355339,  0.35355339,  0.35355339],
       [ 0.35355339, -0.35355339, -0.35355339,  0.35355339, -0.35355339,
         0.35355339,  0.35355339, -0.35355339]])

Controlled Gates

In [10]:
control = 1
target = 2
sim.cNot(control, target)
sim.cNot(1,2)

sim.cNot([1,2],3)
sim.ccNot(1,2,3)  # alias

sim.cHad(1,2)
sim.cZ(1,2)

angle = 90  # deg
sim.cPhase(angle, 1, 2) # phase control target
sim.cRx(angle, 1, 2)
sim.cRy(angle, 1, 2)
sim.cRz(angle, 1, 2)

control = 1
swap1 = 2
swap2 = 3
sim.cSwap(control,swap1,swap2)



array([[1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j, 0.+0.j],
       [0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 0.+0.j, 1.+0.j]])